version: '3.7'

services:
  mq:
    image: ibmcom/mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: password
    ports:
      - target: 1414
        published: 1414
      - target: 9443
        published: 9443
